name: jupyter_dashboards_workshop
channels:
  - conda-forge
  - defaults
  - tim_shawver
dependencies:
  - python>3.6
  - notebook>5.2
  - jupyter_dashboards
  - jupyter_dashboards_bundlers
  - folium
  - ipywidgets=7
  - qgrid
  - plotly