name: jupyter_dashboards_workshop
channels:
  - defaults
  - conda-forge
  - tim_shawver
dependencies:
  - notebook>5.2
  - jupyter_dashboards
  - jupyter_dashboards_bundlers
  - folium
  - ipywidgets
  - qgrid